// Regenerates src/lib/database.types.ts from the linked Supabase project.
// Run this after every migration: npm run types:db
// The file is only replaced if generation succeeds, so a failure never leaves it empty.
import { spawnSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const result = spawnSync('npx', ['supabase', 'gen', 'types', 'typescript', '--linked', '--schema', 'public'], {
  encoding: 'utf8',
});

if (result.status !== 0 || !result.stdout.includes('export type Database')) {
  console.error('Could not generate types. Run `npx supabase login` and `npx supabase link --project-ref <ref>` first.');
  console.error(result.stderr?.slice(0, 1000));
  process.exit(1);
}

const header = '// Generated by `npm run types:db` from the Supabase schema. Do not edit by hand.\n';
writeFileSync('src/lib/database.types.ts', header + result.stdout);
console.log('Wrote src/lib/database.types.ts');
